const colors = {
    RIPLEY_GUINDA: '#741472',
    RIPLEY_AMARILLO: '#FFD400',
    RIPLEY_SALMON: '#F15B5B',
    RIPLEY_ROJO: '#CE171E',
    RIPLEY_PLATEADO: '#CFD4D8',
    RIPLEY_VIOLETA: '#5E388A',
    RIPLEY_PURPURA: '#7C3F88',
    ALT_MORADO: '#9240C9',
    ALT_VIOLETA: '#70578B',
    TEXTOS_PRIMARIO: '#333333',
    TEXTOS_SECUNDARIO: '#6A6A6A',
    TEXTOS_TERCIARIO: '#999999',
    TEXTOS_NEGATIVO: '#FFFFFF',
    FONDOS_BLANCO: '#FFFFFF',
    FONDOS_HUESO: '#F8F8F8',
    FONDOS_GRIS_CLARO: '#EFEFEF',
    OTROS_BORDER: '#CCCCCC',
    ALT_BANCO_RIPLEY_MORADO_1: '#5E388A',
    ALT_BANCO_RIPLEY_MORADO_2: '#7C3F88',
    ALT_BANCO_RIPLEY_ROJO: '#EE2737',
    ALT_PLATEADO_75: '#B7BCBF'
}

export default colors
